[phases.setup]
nixPkgs = [
  "nss",
  "nspr",
  "atk",
  "at-spi2-atk",
  "libx11",
  "libxcomposite",
  "libxdamage",
  "libxrandr",
  "mesa",
  "alsa-lib",
  "pango",
  "cairo",
  "cups",
  "libdrm",
  "libxfixes",
  "libxkbcommon",
  "gtk3"
]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npx playwright install chromium"]

[start]
cmd = "npm start"
