[phases.setup]
aptPkgs = [
  "libnspr4",
  "libnss3",
  "libatk1.0-0",
  "libatk-bridge2.0-0",
  "libx11-xcb1",
  "libxcomposite1",
  "libxdamage1",
  "libxrandr2",
  "libgbm1",
  "libasound2",
  "libpangocairo-1.0-0",
  "libpango-1.0-0",
  "libcairo2",
  "libcups2",
  "libdrm2",
  "libxfixes3",
  "libxkbcommon0",
  "libgtk-3-0"
]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npx playwright install chromium"]

[start]
cmd = "npm start"
